[supervisord]
nodaemon=true

[program:core]
command=/app/core -c /app/config.json
autostart=true
autorestart=true

[program:cloudflared]
command=cloudflared tunnel --url http://localhost:8080
autostart=true
autorestart=true